##################################################
# file: TimeServer_types.py
#
# schema types generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#    /usr/bin/wsdl2py soap.wsdl
#
##################################################

import ZSI
import ZSI.TCcompound
from ZSI.schema import LocalElementDeclaration, ElementDeclaration, TypeDefinition, GTD, GED

##############################
# targetNamespace
# urn:ZSI
##############################

class ns0:
    targetNamespace = "urn:ZSI"

    class Time_Dec(ZSI.TCcompound.ComplexType, ElementDeclaration):
        literal = "Time"
        schema = "urn:ZSI"
        def __init__(self, **kw):
            ns = ns0.Time_Dec.schema
            TClist = [ZSI.TC.AnyType(pname=(ns,"value"), aname="_value", minOccurs=0, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:ZSI","Time")
            kw["aname"] = "_Time"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self,None,TClist,inorder=0,**kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self._value = None
                    return
            Holder.__name__ = "Time_Holder"
            self.pyclass = Holder

# end class ns0 (tns: urn:ZSI)
