##################################################
# file: TimeServer_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py soap.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from TimeServer_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
TimeRequest = GED("urn:ZSI", "Time").pyclass

TimeResponse = GED("urn:ZSI", "Time").pyclass


# Service Skeletons
class TimeServer(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_Time(self, ps, **kw):
        request = ps.Parse(TimeRequest.typecode)
        return request,TimeResponse()

    soapAction['Time'] = 'soap_Time'
    root[(TimeRequest.typecode.nspname,TimeRequest.typecode.pname)] = 'soap_Time'

